### ISSUE TITLE
Errors Running Bootstrap with Topic Modeling

### ISSUE THREAD

**Issue by aaronsadholz** [edublancas/song-lyrics#35]
Tried to run everything overnight. Got this error. 

./bootstrap: line 104: ./topic_modeling: No such file or directory

When I change it to:

./process/transform/topic_modeling

I get this error:

(py3) dyn-129-236-223-140:song-lyrics spare$ make bootstrap
echo 'Boostrapping project...'
Boostrapping project...
./bootstrap
Load bag_of_words_top_1000.feather
Traceback (most recent call last):
  File "./process/transform/topic_modeling", line 10, in <module>
    '../../data/transform/bag_of_words_top_1000.feather')
  File "/Users/spare/anaconda3/envs/py3/lib/python3.6/site-packages/pandas/io/feather_format.py", line 112, in read_feather
    return feather.read_dataframe(path, nthreads=nthreads)
  File "/Users/spare/anaconda3/envs/py3/lib/python3.6/site-packages/pyarrow/feather.py", line 131, in read_feather
    reader = FeatherReader(source)
  File "/Users/spare/anaconda3/envs/py3/lib/python3.6/site-packages/pyarrow/feather.py", line 43, in __init__
    self.open(source)
  File "feather.pxi", line 80, in pyarrow.lib.FeatherReader.open
  File "io.pxi", line 798, in pyarrow.lib.get_reader
  File "io.pxi", line 473, in pyarrow.lib.memory_map
  File "io.pxi", line 452, in pyarrow.lib.MemoryMappedFile._open
  File "error.pxi", line 79, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Failed to open local file: ../../data/transform/bag_of_words_top_1000.feather , error: No such file or directory

In topic modeling script, the code to load bag_of_words_top_1000.feather is

bag_of_words_top_1000 = pd.read_feather(
    '../../data/transform/bag_of_words_top_1000.feather')

I'm pretty confused right now. Any ideas @edublancas ?

**Comment by edublancas** [comment]
My bad, the correct way is `./process/transform/topic_modeling`, you are getting the error because when running bootstrap the root folder is the current directory, so I just changed the path to the file and it runs now
